<?php
/**
 * Created by PhpStorm.
 * User: wskyt
 * Date: 2017/2/24
 * Time: 15:14
 */

require ('page.inc');

class ServicesPage extends Page {
    private $row2buttons = array(
        "Re-engineering"        => "reengineering.php",
        "Standards Compliance"  => "standards.php",
        "Buzzword Compliance"   => "mission.php"
    );

    public function Display()
    {
//        parent::Display(); // TODO: Change the autogenerated stub
        echo "<html>\n<head>\n";
        $this->DisplayTile();
        $this->DisplayKeywords();
        $this->DisplayStyles();
        echo "</head>\n<body>\n";
        $this->DisplayHeader();
        $this->DisplayMenu($this->buttons);
        $this->DisplayMenu($this->row2buttons);
        echo $this->content;
        $this->DisplayFooter();
        echo "</body>\n</html>\n";
    }
}

$services = new ServicesPage();

$services->content = "<p>lalala.</p>";

$services->Display();